# Generated by Django 3.0.1 on 2019-12-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', models.TextField()),
                ('attack', models.IntegerField()),
                ('base_egg_steps', models.IntegerField()),
                ('base_happiness', models.IntegerField()),
                ('base_total', models.IntegerField()),
                ('capture_rate', models.IntegerField()),
                ('classification', models.TextField()),
                ('defense', models.IntegerField()),
                ('experience_growth', models.IntegerField()),
                ('height_m', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hp', models.IntegerField()),
                ('japanese_name', models.TextField()),
                ('name', models.TextField()),
                ('percentage_male', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pokedex_number', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type1', models.TextField()),
                ('type2', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('generation', models.IntegerField()),
                ('is_legendary', models.IntegerField()),
            ],
        ),
    ]
